### PR TITLE
adding dad jokes

### PR DESCRIPTION
**Pull request by ThomasStalley**

### CODE REVIEW

**Comment by alexobrien20** [comment]
Where are the tests? @ThomasStalley

**Comment by ThomasStalley** [comment]
> Where are the tests? @ThomasStalley

   ¯\\_(ツ)_/¯
   never heard of him

**Comment by LegalEd** [comment]
Wait. I just realised your forked the repo! 🤣 Is this a hostile takeover?

**Review by LegalEd — APPROVED** [review]
LGTM!

**Comment by ThomasStalley** [comment]
> Wait. I just realised your forked the repo! 🤣 Is this a hostile takeover?

Git-tatorship ❗️

**Comment by ThomasStalley** [comment]
(or just rubbish at git...)

**Comment by LegalEd** [comment]
Normally a fork is when you like a project but want to take it in a different direction from the original creators. 🤣

**Comment by ThomasStalley** [comment]
> Normally a fork is when you like a project but want to take it in a different direction from the original creators. 🤣

Ah I see, thanks!

p.s. I am the captain now 🏴‍☠️

**Pull request merged**
